module.exports = {
  HIDE_MAIN_WINDOW: 'HIDE_MAIN_WINDOW',
  OPEN_SETTINGS_WINDOW: 'OPEN_SETTINGS_WINDOW',
  CLOSE_SETTINGS_WINDOW: 'CLOSE_SETTINGS_WINDOW',
  RUN_COMMAND: 'RUN_COMMAND',
  RUN_COMMAND_DONE: 'RUN_COMMAND_DONE',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS'
};
