module.exports = {
  HIDE: 'HIDE',
  CLOSE: 'CLOSE',
  RUN_COMMAND: 'RUN_COMMAND',
  RUN_COMMAND_DONE: 'RUN_COMMAND_DONE',
  OPEN_SETTINGS_WINDOW: 'OPEN_SETTINGS_WINDOW',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS'
};
